### ISSUE TITLE
Cannot download prices anymore since last week "error 404"

### ISSUE THREAD

**Issue by ThomasPade** [EnergieID/entsoe-py#244]
Dear Entsoe Community,

My colleagues and me have the same issue since last week roughly . We cannot download the data anymore. I renewed already the entsoe token but it seems that this is not token related. On every request , which was working before , I get the following failure message

HTTPError: 404 Client Error: 404 for url: https://transparency.entsoe.eu/api?documentType=A44&in_Domain=10YBE----------2&out_Domain=10YBE----------2&securityToken=348154d2-8c98-44a3-b7c6-ed5115387238&periodStart=202212312300&periodEnd=202301312300

![entsoe example](https://user-images.githubusercontent.com/92080171/220332354-759aec0d-d04d-4ebf-9120-3ce02b1095b8.PNG)

Would be great if somebody could help.

Thank you

Thomas Pade

**Comment by fboerman** [comment]
Hi you are kindly requested to always test with the latest package version before opening an issue. Your error is due to changing of base url for the app which has been fixed some versions ago. Please update your installation.

Also you leaked your api key in the error.

-------- Original Message --------

**Comment by ThomasPade** [comment]
Thank your very much for your fast reply. I appreciate it a lot. I will create a new token  . Thanks for the hint !

**Comment by ThomasPade** [comment]
Installed the latest package version "pip install entsoe-py" but its still not working . Im getting the same failure message .

![image](https://user-images.githubusercontent.com/92080171/220338944-1906d81d-4a36-463e-9f47-385fd3b39ce4.png)

**Comment by fboerman** [comment]
You need to do pip install -U entsoe-py and then restart your running python shell if you were using one.

-------- Original Message --------

**Comment by KaneM97** [comment]
Also having the same issue, my version worked until a couple of days ago.  The version I am using is 0.5.9 which is the latest version on pip but I still retrieve the error below 
![image](https://user-images.githubusercontent.com/90043894/220341183-481ec126-40a2-427d-bcca-b6d9f1202bea.png)

**Comment by fboerman** [comment]
Hi, the url is hardcoded in the package. If your error shows the old url like in your screenshot you are not using the latest version. Please check your installation.

-------- Original Message --------

**Comment by ThomasPade** [comment]
I installed the newest version of entsoe py . Uninstalled the old one and installed again . Now I have 0.5.9 installed. I'm getting still a failure message but a different one . Could you please help.
![image](https://user-images.githubusercontent.com/92080171/220384441-0d077db1-eea8-472b-8fc3-90b87d59b0fa.png)

And here my installation  . Is there something wrong?
![image](https://user-images.githubusercontent.com/92080171/220384884-932fdfb6-2e0b-4a30-afb8-aa22287b75f3.png)

Thank you

**Comment by ThomasPade** [comment]
Got it ! Great! Thanks very much . Its working now
